# SERVICES
keepalived:
  labels:
    io.rancher.scheduler.global: 'true'
  environment:
    - VIRTUAL_IP=172.17.8.150
    - VIRTUAL_MASK=24
    - CHECK_IP=any
    - CHECK_PORT=8080
    - VRID=150
    - INTERFACE=eth0
  tty: true
  build: docker-keepalived
  stdin_open: true
  net: host
  cap_add:
  - NET_ADMIN
  - NET_BROADCAST

traefik:
  ports:
    - 8080:8080/tcp
    - 80:80/tcp
    - 443:443/tcp
  image: traefik:1.7.14-alpine
